# Required metadata
sonar.projectKey=qucs-s
sonar.projectName=qucs-s
sonar.projectVersion=25.1.2

# Source code information
sonar.sources=qucs
sonar.language=cpp

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# SCM (optional)
sonar.scm.provider=git
