# Required metadata
sonar.projectKey=qucs
sonar.projectName=qucs
sonar.projectVersion=1.0

# Source code information
sonar.sources=qucs
sonar.language=cpp

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# SCM (optional)
sonar.scm.provider=git
